# The ID of the chat to post to. The bot must be in the chat
chatId: '-1001375311913'

# The minimum length of message to consider posting
minMessageLength: 30

greetings:
  - Yo
  - Yo guys
  - Hey guys
  - Hey everyone
  - Omg
  - Guys
  - Wait what.
  - LOL
  - Holy shit
  - Aw shit
  - Bruh
  - Damn

intros:
  - Remember when [user] said
  - Remember that time when [user] said
  - I randomly stumbled on this thing that [user] said
  - Still can’t believe that [user] said
  - I still haven’t gotten over that time that [user] said
  - Not to keep dwelling on it, but I never forgot that [user] said
  - It really was crazy AF when [user] said
  - I gotta say, I never moved past it when [user] said
  - It has me in stitches when [user] said
  - I'm here scratching my head that [user] said
  - Gotta be honest, it creeped me the fuck out when [user] said
  - It really made an impression on me that [user] said
  - We need to talk about how [user] said
  - [user] wasn't fucking around when he said
