# The database file pathto store state in
dbPath: ./database.sqlite

# The JSON files that the bot will read old messages from
messageFiles:
  facebook: ./facebook_*.json

# The telegram chat ID the bot should be active in
chatId: '-1001375311913'

# The minimum length a message must be to be considered a candidate to be
# quoted
minMessageLength: 30

# The messages the bot will oepn with
greetings:
  - Yo
  - Yo guys
  - Hey guys
  - Hey everyone
  - Omg
  - Guys
  - Wait what.
  - LOL
  - Holy shit
  - Aw shit
  - Bruh
  - Damn

# The message following the greeting, just before posting the quote
intros:
  - Remember when [user] said
  - Remember that time when [user] said
  - I randomly stumbled on this thing that [user] said
  - Still can’t believe that [user] said
  - I still haven’t gotten over that time that [user] said
  - Not to keep dwelling on it, but I never forgot that [user] said
  - It really was crazy AF when [user] said
  - I gotta say, I never moved past it when [user] said
  - It has me in stitches when [user] said
  - "I'm here scratching my head that [user] said"
  - Gotta be honest, it creeped me the fuck out when [user] said
  - It really made an impression on me that [user] said
  - We need to talk about how [user] said
  - "[user] wasn't fucking around when he said"
