name: docker build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest image
        run: docker pull evanpurkhiser/doppovich-bot:latest
      - name: Build
        run: docker build --tag=evanpurkhiser/doppovich-bot:latest .
      - name: Publish
        run: |
          docker login --username=evanpurkhiser --password-stdin <<< "${{ secrets.DOCKER_HUB_TOKEN }}"
          docker push evanpurkhiser/doppovich-bot:latest
