name: telegram notif
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_COMMIT_NOTIF_TO }}
          token: ${{ secrets.TELEGRAM_COMMIT_NOTIF_TOKEN }}
          message: |
            ${{ github.actor }} commited: https://github.com/${{ github.repository }}/commit/${{github.sha}}
